pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                sh 'echoa "Hello Jenkins"'
                sh 'date'
            }
        }
    }
}
