pipeline {
    agent any
    
    tools {
        go 'go-1.21'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('UnitTest Backend -Danh') {
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
